export const ListLanguage = {
  "html": "HTML",
  "css": "CSS",
  "js": "JavaScript",
  "ts": "TypeScript",
  "jsx": "React JSX",
  "tsx": "React TSX",
  "scss": "Sass (Scss)",
  "graphql": "GraphQL",
  "json": "JSON",
  "php": "PHP",
  "sql": "SQL",
  "tsconfig": "TSConfig",
  "uri": "URI",
  "url": "URL",
  "xml": "XML",
  "svg": "SVG",
  "sass": "Sass (Sass)",
  "py": "Python",
  "regex": "Regex",
  "ignore": ".ignore",
  "gitignore": ".gitignore",
  "npmignore": ".npmignore",
  "mongodb": "MongoDB",
  "nginx": "nginx",
  "ejs": "EJS",
  "hbs": "Handlebars",
  "aspnet": "ASP.NET (C#)",
  "dotnet": "C#",
  "cpp": "C++",
  "django": "Django/Jinja2",
  "dockerfile": "Docker",
  "sol": "Solidity (Ethereum)",
  // "xlsx": "Excel Formula",
  // "xls": "Excel Formula",
  // "hcl": "HCL",
  // "hlsl": "HLSL",
  // "http": "HTTP",
  // "jsdoc": "JSDoc",
  // "json5": "JSON5",
  // "jsonp": "JSONP",
  // "jsstacktrace": "JS stack trace",
  // "js-templates": "JS Templates",
  // "kts": "Kotlin Script",
  // "kt": "Kotlin",
  // "md": "Markdown",
  // "matlab": "MATLAB",
  // "nsis": "NSIS",
  // "objc": "Objective-C",
  // "phpdoc": "PHPDoc",
  // "php-extras": "PHP Extras",
  // "powershell": "PowerShell",
  // "rb": "Ruby",
  // "sh-session": "Shell session",
  // "vim": "vim",
  // "visual-basic": "Visual Basic",
  // "xml-doc": "XML doc (.net)",
  // "xquery": "XQuery",
  // "yaml": "YAML",
  // "yml": "YAML",
  // "yang": "YANG"
}