# OUTPUT_LANG_INDEX start from 0
generator-localization-code-memory-admin:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=15mJ3eHzyPNn2aX0UIuG6C9ZwKRWZsL9cGQhNiX9kKLU GID_ID=admin OUTPUT_FOLDER=../src/i18n/locales/vn.json
